stages:
  - stylecheck
  - test
  - deploy

.conda_env: &conda_env
    before_script:
        # update conda
        - conda config --set always_yes yes
        - conda update -q conda

        # create and activate environment
        - conda create -q -n testenv_${CI_PIPELINE_ID}_${CI_JOB_NAME}_py${PYTHON_VERSION_TO_USE//./} python=${PYTHON_VERSION_TO_USE}
        - source activate testenv_${CI_PIPELINE_ID}_${CI_JOB_NAME}_py${PYTHON_VERSION_TO_USE//./}
    after_script:
        # remove environment
        - conda env remove --name testenv_${CI_PIPELINE_ID}_${CI_JOB_NAME}_py${PYTHON_VERSION_TO_USE//./}

.test_template: &test_template
    <<: *conda_env
    stage: test
    rules:
        - if: $CI_MERGE_REQUEST_TITLE =~ /^(Draft:|WIP:|\[Draft\]|\[WIP\])/
          when: manual
        - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE !~ /^(Draft:|WIP:|\[Draft\]|\[WIP\])/
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        - if: $CI_PIPELINE_SOURCE == "schedule"
    script:
        # for debugging, list all environment variables
        # - export

        # install packages (use conda to avoid time-consuming installations)
        - conda install -q pytest pytest-cov
        - python -m pip install -q pytest-html

        # pytorch and detectron2
        - |
          if [ "${PYTHON_VERSION_TO_USE}" == "3.8" ]; then
            # torch 2.4.1 was the last version for Python 3.8
            python -m pip install torch==2.4.1 torchvision==0.19.1 --index-url https://download.pytorch.org/whl/cpu
            python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
          else
            python -m pip install torch==2.10.0 torchvision==0.25.0 --index-url https://download.pytorch.org/whl/cpu
            python -m pip install --no-build-isolation 'git+https://github.com/facebookresearch/detectron2.git'
          fi

        # check conda installation
        - conda info
        - conda list

        # the home folder is relatively small, so for large checkpoints, we need to use a different folder
        - export DEFAULT_CACHE_BASEPATH=/local/.cache/

        # install package (and all missing dependencies)
        - python -m pip install -q --editable .[withopencv,test]

        # test package (opt: get coverage)
        - |
          if [ "${REPORT_COVERAGE}" == "true" ]; then
              py.test tests/ -rx -s -vv --cov=${CI_PROJECT_NAME//-/_} --cov-report html --cov-report term --html=report_py${PYTHON_VERSION_TO_USE//./}.html --self-contained-html
          else
              py.test tests/ -rx -s -vv --html=report_py${PYTHON_VERSION_TO_USE//./}.html --self-contained-html
          fi
    coverage: '/^TOTAL.*\s+(\d+\%)$/'
    artifacts:
        when: always
        paths:
            - report_py${PYTHON_VERSION_TO_USE//./}.html
            - htmlcov

.test_dataset_template: &test_dataset_template
    <<: *conda_env
    stage: test
    rules:
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: never
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          when: manual
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
        DATASET_PATH: /local/test_location_for_nicr_scene_analysis_datasets
    script:
        # for debugging, list all environment variables
        # - export

        # install packages (use conda to avoid time-consuming installations)
        - conda install -q pytest

        # pytorch and detectron2
        - |
          if [ "${PYTHON_VERSION_TO_USE}" == "3.8" ]; then
            # torch 2.4.1 was the last version for Python 3.8
            python -m pip install torch==2.4.1 torchvision==0.19.1 --index-url https://download.pytorch.org/whl/cpu
            python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
          else
            python -m pip install torch==2.10.0 torchvision==0.25.0 --index-url https://download.pytorch.org/whl/cpu
            python -m pip install --no-build-isolation 'git+https://github.com/facebookresearch/detectron2.git'
          fi

        # check conda installation
        - conda info
        - conda list

        # the home folder is relatively small, so for large checkpoints, we need to use a different folder
        - export DEFAULT_CACHE_BASEPATH=/local/.cache/

        # install package (and all missing dependencies)
        - python -m pip install -q --editable .[withopencv,withpreparation,withauxiliarydata,test]

        # run test
        - OUTPUT_PATH="${DATASET_PATH}"
        - FORCE_RECREATE=true
        - RUN_TESTS=true
        - RUN_COMPARISONS=true
        - CLEAN_UP=true
        - cd tests
        - source test_datasets.sh

        - ${TEST_TO_RUN}

    after_script:
        - echo "Cleaning up ${DATASET_PATH}"
        - rm -rf "${DATASET_PATH}"
        - !reference [.conda_env, after_script]

style_check:
    <<: *conda_env
    stage: stylecheck
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        - if: $CI_PIPELINE_SOURCE == "schedule"
    variables:
        PYTHON_VERSION_TO_USE: "3.12"     # ubuntu24 default
    script:
        # install packages
        - python -m pip install ruff

        # run style check
        - ruff check .

tests_py38:    # ubuntu20
    <<: *test_template
    variables:
        PYTHON_VERSION_TO_USE: "3.8"
        REPORT_COVERAGE: "false"

tests_py310:    # ubuntu22
    <<: *test_template
    variables:
        PYTHON_VERSION_TO_USE: "3.10"
        REPORT_COVERAGE: "false"

tests_py312:    # ubuntu24
    <<: *test_template
    variables:
        PYTHON_VERSION_TO_USE: "3.12"
        REPORT_COVERAGE: "true"

test_dataset:
    <<: *test_dataset_template
    parallel:
        matrix:
        - PYTHON_VERSION_TO_USE: [ "3.12" ]
          TEST_TO_RUN:
          # datasets and versions
          - test_ade20k
          - test_cityscapes
          - test_coco
          - test_hypersim  # all hypersim versions
          - test_hypersim_tilt_shift
          - test_hypersim_no_tilt_shift
          - test_nyuv2
          - test_scannet
          - test_scenenet_rgbd
          - test_sunrgbd  # all sunrgbd versions
          - test_sunrgbd_emsanet
          - test_sunrgbd_panopticndt
          # auxiliary_data
          - test_nyuv2_with_auxiliary_data
          # mapping
          - test_mapping_hypersim
          - test_mapping_scannet

update_pip_package:
    <<: *conda_env
    stage: deploy
    rules:
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: never
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          when: manual
    variables:
        PYTHON_VERSION_TO_USE: "3.12"     # ubuntu24 default
    script:
        - python -m pip install twine>=5.0.0 pkginfo>=1.10.0

        # build package
        - python -m pip install build
        - python -m build --sdist --wheel

        # upload package
        - export TWINE_USERNAME=${TWINE_USERNAME}
        - export TWINE_PASSWORD=${TWINE_PASSWORD}
        - python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${PACKAGE_REGISTRY}/packages/pypi dist/*
